In [16]:
import numpy as np


In [4]:
x+y

32

In [7]:
a=[1,2,3,4,5]

In [11]:
print(a)

[1, 2, 3, 4, 5]


In [19]:
rarr = np.random.randint(0,50,60)

In [20]:
rarr

array([22, 12,  8, 42, 41, 25, 44, 49, 27, 21, 31, 39, 31, 13, 11, 38, 46,
       25, 18, 26, 26, 36, 23,  2, 31, 47, 14, 48, 41, 33, 10, 46, 20, 49,
       30,  4, 26,  3, 38, 31, 23, 13, 26, 34, 23, 26, 17, 19,  0, 49,  2,
       41,  9, 11,  6, 40, 14, 29, 27, 27])

In [24]:
rarr.dtype

dtype('int32')

In [25]:
rarr[4]

41

In [26]:
rarr[5]+rarr[4]

66

In [29]:
sub=rarr[3:7]

In [30]:
sub

array([42, 41, 25, 44])

In [31]:
rarr

array([22, 12,  8, 42, 41, 25, 44, 49, 27, 21, 31, 39, 31, 13, 11, 38, 46,
       25, 18, 26, 26, 36, 23,  2, 31, 47, 14, 48, 41, 33, 10, 46, 20, 49,
       30,  4, 26,  3, 38, 31, 23, 13, 26, 34, 23, 26, 17, 19,  0, 49,  2,
       41,  9, 11,  6, 40, 14, 29, 27, 27])

In [32]:
rarr[3:7]=555

In [33]:
rarr

array([ 22,  12,   8, 555, 555, 555, 555,  49,  27,  21,  31,  39,  31,
        13,  11,  38,  46,  25,  18,  26,  26,  36,  23,   2,  31,  47,
        14,  48,  41,  33,  10,  46,  20,  49,  30,   4,  26,   3,  38,
        31,  23,  13,  26,  34,  23,  26,  17,  19,   0,  49,   2,  41,
         9,  11,   6,  40,  14,  29,  27,  27])

In [34]:
sub

array([555, 555, 555, 555])

In [35]:
rarr= np.random.randint(1,100,20)

In [36]:
rarr

array([26, 35, 11, 33, 60, 34, 77, 52, 34, 45, 93, 57, 89, 92, 67, 35, 16,
       86, 59, 89])

In [39]:
y=sub.copy()

In [40]:
y

array([555, 555, 555, 555])

In [41]:
len(rarr)

20

In [42]:
matrix=rarr.reshape(4,5)

In [43]:
matrix


array([[26, 35, 11, 33, 60],
       [34, 77, 52, 34, 45],
       [93, 57, 89, 92, 67],
       [35, 16, 86, 59, 89]])

In [45]:
matrix[1:3]

array([[34, 77, 52, 34, 45],
       [93, 57, 89, 92, 67]])

In [49]:
submatrix=matrix[1:3]

rarr.shape

In [50]:
rarr.shape

(20,)